name: Test Main Branch

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Create test network
              run: docker network create test-net

            - name: Start Redis container
              run: docker run -d --name redis --network test-net redis

            - name: Wait for Redis to be ready
              run: |
                until docker exec redis redis-cli ping | grep PONG; do
                  echo "Waiting for Redis..."
                  sleep 2
                done

            - name: Build application container
              run: docker build -f Test.Dockerfile -t darkchat-test .

            - name: Run tests in container
              run: |
                docker run --rm --network test-net -e REDIS_HOST=redis -e REDIS_PORT=6379 darkchat go test -v ./...
